// Mapeamento de documentos obrigatórios por tipo de fornecedor
// Adapte conforme necessário!

export type TipoFornecedor =
  | 'AGENCIADOR DE CARGA'
  | 'AGENTE'
  | 'ARQUITETURA - REGULARIZAÇÃO'
  | 'ASSESSORIA JURÍDICA'
  | 'ASSESSORIA PARA LICENCIAMENTO'
  | 'ASSISTÊNCIA EM MEDICINA E SEGURANÇA DO TRABALHO'
  | 'BASE & COLIGADA - A'
  | 'BASE & COLIGADA - B'
  | 'BASE COLIGADA'
  | 'BASE COLIGADA - DUPLICATA'
  | 'BASE COLIGADA - AT'
  | 'BASE COLIGADA - OU'
  | 'BASE COLIGADA - TR'
  | 'CALIBRAÇÃO DE EQUIPAMENTOS'
  | 'CLIENTE NATURA - FORNECEDOR DE INSUMO LOGÍSTICO'
  | 'COIFA - SERVIÇO ADMINISTRADO PELO REFEITÓRIO (TERCEIRIZADO) - CDCO'
  | 'COLETA de ÓLEO (ADMINISTRADO PELA EMPRESA TERCEIRIZADA DO REFEITÓRIO) - CDCO'
  | 'CONTROLE AMBIENTAL'
  | 'CONTROLE DE PONTO'
  | 'DESENTUPIDOR SANITÁRIO'
  | 'DIVERSOS'
  | 'DOCUMENTAÇÃO LEGAL - FILIAL (CDBD)'
  | 'DOCUMENTAÇÃO LEGAL - FILIAL (CDJD)'
  | 'DOCUMENTAÇÃO LEGAL - FILIAL (CDVG)'
  | 'DOCUMENTAÇÃO LEGAL - MATRIZ (CDCO)'
  | 'EMPRESA CERTIFICADORA'
  | 'EMPRESA ESTATAL'
  | 'ENGENHARIA E CONSTRUÇÃO'
  | 'ERGONOMIA E GINASTICA LABORAL'
  | 'ESCRITÓRIO DE CONTABILIDADE'
  | 'ETC - EMPRESA DE TRANSPORTE RODOVIÁRIO DE CARGAS'
  | 'FABRICANTE DE CADEIRA'
  | 'FILIAL'
  | 'FORNECEDOR DE INSUMOS LOGÍSTICOS'
  | 'FORNECEDOR DE UNIFORMES'
  | 'FROTA AGREGADA'
  | 'FUNCIONÁRIO - OP'
  | 'GÁS - EMPRESA TERCEIRIZADA PELO REFEITÓRIO (GESTÃO TERCEIRIZADA) - CDCO'
  | 'LIMPEZA - SERVIÇO TERCEIRIZADO'
  | 'Locação de Suco'
  | 'LOCADORA DE GALPÕES'
  | 'MANUTENÇÃO DE GERADORES'
  | 'MANUTENÇÃO DE VEICULOS'
  | 'MÃO DE OBRA TEMPORÁRIA'
  | 'NUTRICIONISTA'
  | 'PENSÃO ALIMENTÍCIA'
  | 'PESSOA JURÍDICA - PJ'
  | 'PMOC - LIMPEZA E MANUTENÇÃO DE AR-CONDICIONADO'
  | 'PORTARIA - SERVIÇOS TERCEIRIZADO'
  | 'PRODUÇÃO CINEMATOGRÁFICAS, AUDIOVISUAIS  E PUBLICITÁRIAS'
  | 'RECICLAGEM E SUSTENTABILIDADE'
  | 'REFEITÓRIO COTIA'
  | 'REFEITÓRIO DE CDVG (Gestão Terceirizada)'
  | 'SEGURADORA'
  | 'SEGURANÇA TECNOLÓGICA'
  | 'SERVIÇOS E SOLUÇÕES AMBIENTAIS - REGULARIZAÇÃO'
  | 'TAC - TRANSPORTADOR AUTÔNOMO DE CARGAS'
  | 'TI - SERVIÇOS'
  | 'TRANSPORTADORA - NATURA'
  | 'TRANSPORTADORES'
  | 'VALE-ALIMENTAÇÃO/VALE-TRANSPORTE'
  | 'VISTORIA DAS INSTALAÇÕES ELÉTRICAS E ELABORAÇÃO DE LAUDOS ELÉTRICOS';

export interface DocumentoObrigatorio {
  id: string;
  nome: string;
  vencimentoObrigatorio?: boolean; // Se o documento exige vencimento
  prazoPadrao?: number; // Prazo padrão para renovação do documento
  referenciaLegal?: string; // Referência legal para o documento
  lembreteDias?: number; // Quantos dias antes do vencimento o status muda para pendente
}

export const documentosObrigatorios: Record<TipoFornecedor, DocumentoObrigatorio[]> = {
  'AGENCIADOR DE CARGA': [
    { id: 'antt', nome: 'ANTT' },
    { id: 'apolice-seguros', nome: 'APÓLICE DE SEGUROS' },
    { id: 'comprovante-endereco', nome: 'COMPROVANTE DE ENDEREÇO' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'proposta-comercial', nome: 'PROPOSTA COMERCIAL OU CONTRATO DE PRESTAÇÃO DE SERVIÇO' }
  ],
  'AGENTE': [
    { id: 'analise-financeira', nome: 'Análise Financeira - pelo departamento Financeiro' },
    { id: 'antt', nome: 'ANTT' },
    { id: 'apolice-evidencia', nome: 'Apólice de Seguro ou evidencia da Diretoria Postall assumindo os riscos em caso sinistro' },
    { id: 'avcb-ou-isencao', nome: 'AVCB ou documento de isenção' },
    { id: 'cartao-cnpj', nome: 'Cartao CNPJ' },
    { id: 'contrato-social', nome: 'Contrato Social' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'ficha-cadastral', nome: 'Ficha Cadastral' },
    { id: 'licenca-funcionamento', nome: 'Licença de Funcionamento' },
    { id: 'registro-treinamento', nome: 'Registro de treinamento - Integração' },
    { id: 'relatorio-visita', nome: 'Relatório da Visita Técnica' }
  ],
  'ARQUITETURA - REGULARIZAÇÃO': [
    { id: 'alvara', nome: 'Alvará de Funcionamento.' },
    { id: 'avcb', nome: 'AVCB.' },
    { id: 'carteira-identidade-rt', nome: 'Carteira de Identidade Responsável Técnico' },
    { id: 'cnpj-atualizado', nome: 'CNPJ Atualizado (Ativo).' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'proposta-comercial-cdco', nome: 'PROPOSTA COMERCIAL - BAIXA E ASSUNÇÃO RT CDCO' },
    { id: 'proposta-comercial-cdvg', nome: 'PROPOSTA COMERCIAL - BAIXA E ASSUNÇÃO RT CDVG' }
  ],
  'ASSESSORIA JURÍDICA': [
    { id: 'alvara-licenca', nome: 'ALVARÁ/LICENÇA DE FUNCIONAMENTO' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'comprovante-inscricao', nome: 'COMPROVANTE DE INSCRIÇÃO E DE SITUAÇÃOCADASTRAL' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇOS' },
    { id: 'contrato-prest-serv-2', nome: 'Contrato de Prestação de Serviços.' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'registro-oab', nome: 'REGISTRO OAB DOS SÓCIOS' }
  ],
  'ASSESSORIA PARA LICENCIAMENTO': [
    { id: 'avcb', nome: 'AVCB (Auto de Vistoria do Corpo de Bombeiros).' },
    { id: 'certidao-habilidade', nome: 'Certidão Habilidade Técnica' },
    { id: 'cetesb-ou-isenta', nome: 'CETESB ou declaração de isenta' },
    { id: 'cnpj', nome: 'CNPJ' },
    { id: 'contrato-prest-serv-postall', nome: 'Contrato de Prestação de Serviços com a Postall' },
    { id: 'contrato-social', nome: 'Contrato Social' },
    { id: 'ficha-cadastral', nome: 'Ficha Cadastral' }
  ],
  'ASSISTÊNCIA EM MEDICINA E SEGURANÇA DO TRABALHO': [
    { id: 'alvara', nome: 'Alvará de Funcionamento.' },
    { id: 'apolice-ou-contrato', nome: 'APÓLICE DE SEGUROS OU CONTRATO DE PRESTAÇÃO DE SERVIÇOS' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'avcb2', nome: 'AVCB.' },
    { id: 'carteira-identidade-prof', nome: 'Carteira de Identidade Profissional - Enf. Civil - RT' },
    { id: 'certificado-calibracao', nome: 'Certificado de Calibração - Equipamentos.' },
    { id: 'certificado-pcmso', nome: 'CERTIFICADO DO RESPONSÁVEL DE ELABORAÇÃO PCMSO' },
    { id: 'certificado-pcmso2', nome: 'Certificado do Responsável de Elaboração PCMSO.' },
    { id: 'cnpj', nome: 'CNPJ' },
    { id: 'cnpj2', nome: 'CNPJ.' },
    { id: 'contrato-assistencia', nome: 'CONTRATO DE ASSISTENCIA EM MEDICINA E SEGURANÇA DO TRABALHO' },
    { id: 'contrato-prest-serv', nome: 'Contrato de Prestação de Serviços.' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'identidade-engenheiro', nome: 'Identidade Engenheiro - CONFEA CREA' },
    { id: 'laudo-calibracao-decibelimetro', nome: 'LAUDO CALIBRAÇÃO - DECIBELÍMETRO' },
    { id: 'laudo-calibracao-luximetro', nome: 'LAUDO CALIBRAÇÃO - LUXÍMETRO DIGITAL' },
    { id: 'laudo-calibracao-stress', nome: 'LAUDO CALIBRAÇÃO - MEDIDOR DE STRESS TÉRMICO' }
  ],
  'BASE & COLIGADA - A': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO' },
    { id: 'antt', nome: 'ANTT' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ' },
    { id: 'checklist-homologacao', nome: 'CHECKLIST DE HOMOLOGAÇÃO' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'registro-treinamento', nome: 'REGISTRO DE TREINAMENTO' },
    { id: 'sintegra', nome: 'SINTEGRA (INSCRIÇÃO ESTADUAL)' },
    { id: 'teste', nome: 'teste' },
  ],
  'BASE & COLIGADA - B': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO' },
    { id: 'antt', nome: 'ANTT' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ' },
    { id: 'checklist-homologacao', nome: 'CHECKLIST DE HOMOLOGAÇÃO' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'sintegra', nome: 'SINTEGRA (INSCRIÇÃO ESTADUAL)' },
  ],
  'BASE COLIGADA': [
    { id: 'alvara', nome: 'Alvará de Funcionamento.' },
    { id: 'apolice-seguros', nome: 'Apólice de Seguros.' },
    { id: 'avcb', nome: 'AVCB.' },
    { id: 'cnpj-atualizado', nome: 'CNPJ Atualizado (Ativo).' },
    { id: 'contrato-prest-serv', nome: 'Contrato de Prestação de Serviços.' },
    { id: 'faltou-anexo', nome: 'FALTOU UM ANEXO' },
    { id: 'ie', nome: 'Inscrição Estadual - IE' },
  ],
  'BASE COLIGADA - DUPLICATA': [
    { id: 'alvara', nome: 'Alvará de Funcionamento.' },
    { id: 'analise-financeira', nome: 'Análise Financeira - pelo departamento Financeiro' },
    { id: 'antt', nome: 'ANTT' },
    { id: 'apolice-ou-evidencia', nome: 'Apólice de Seguro ou evidencia da Diretoria Postall assumindo os riscos em caso sinistro.' },
    { id: 'avcb', nome: 'AVCB (Auto de Vistoria do Corpo de Bombeiros).' },
    { id: 'cnd-municipal', nome: 'Certidões negativas de débitos  municipais' },
    { id: 'cnd-federal', nome: 'Certidões negativas de débitos e federais' },
    { id: 'cnd-estadual', nome: 'Certidões negativas de débitos estaduais' },
    { id: 'cetesb-ou-isenta', nome: 'CETESB ou declaração de isenta' },
    { id: 'cnpj-ativo', nome: 'CNPJ Ativo.' },
    { id: 'contrato-prest-serv-postall', nome: 'Contrato de Prestação de Serviços com a Postall' },
    { id: 'contrato-prest-serv', nome: 'Contrato de Prestação de Serviços.' },
    { id: 'contrato-social', nome: 'Contrato Social' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'ficha-cadastral', nome: 'Ficha Cadastral' },
    { id: 'ie', nome: 'IE - Inscrição Estadual' },
    { id: 'performance-mensal', nome: 'Perfomance mensal' },
    { id: 'registro-treinamento', nome: 'Registro de Treinamento (Integração)' },
    { id: 'relatorio-visita-tecnica', nome: 'Relatório de Visita Técnica' },
  ],
  'BASE COLIGADA - AT': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Código de Posturas Municipal', lembreteDias: 3 },
    { id: 'antt', nome: 'ANTT', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Resolução ANTT 3.056/09', lembreteDias: 3 },
    { id: 'apolice-seguros', nome: 'APÓLICE DE SEGUROS', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Vigência da apólice', lembreteDias: 3 },
    { id: 'avcb', nome: 'AVCB', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Decreto Estadual (ex: SP: 63.911/18)', lembreteDias: 3 },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ', vencimentoObrigatorio: false },
    { id: 'checklist-homologacao-base', nome: 'CHECKLIST - HOMOLOGAÇÃO DE BASE', vencimentoObrigatorio: false },
    { id: 'cnd-estadual', nome: 'CND ESTADUAL', vencimentoObrigatorio: true, prazoPadrao: 180, referenciaLegal: 'Varia por estado, geralmente 6 meses', lembreteDias: 3 },
    { id: 'cnd-federal', nome: 'CND FEDERAL', vencimentoObrigatorio: true, prazoPadrao: 180, referenciaLegal: 'Art. 47, Lei 8.212/91', lembreteDias: 3 },
    { id: 'cnd-municipal', nome: 'CND MUNICIPAL', vencimentoObrigatorio: true, prazoPadrao: 180, referenciaLegal: 'Varia por município, geralmente 6 meses', lembreteDias: 3 },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Prática de mercado', lembreteDias: 3 },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL', vencimentoObrigatorio: false },
    { id: 'distrato', nome: 'Distrato', vencimentoObrigatorio: false },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Prática de mercado', lembreteDias: 3 },
    { id: 'licenca-ambiental', nome: 'LICENÇA AMBIENTAL', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Resolução CONAMA 237/97', lembreteDias: 3 },
    { id: 'licenca-ambiental-ou', nome: 'LICENÇA AMBIENTAL (OU DISPENSA)', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Resolução CONAMA 237/97', lembreteDias: 3 },
    { id: 'performance-mensal', nome: 'PERFORMANCE MENSAL', vencimentoObrigatorio: false },
    { id: 'registro-treinamento', nome: 'REGISTRO DE TREINAMENTO', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Prática de mercado', lembreteDias: 3 },
    { id: 'sintegra', nome: 'SINTEGRA (INSCRIÇÃO ESTADUAL)', vencimentoObrigatorio: false }
  ],
  'BASE COLIGADA - OU': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Código de Posturas Municipal', lembreteDias: 3 },
    { id: 'antt', nome: 'ANTT', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Resolução ANTT 3.056/09', lembreteDias: 3 },
    { id: 'avcb', nome: 'AVCB', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Decreto Estadual (ex: SP: 63.911/18)', lembreteDias: 3 },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ', vencimentoObrigatorio: false },
    { id: 'checklist-homologacao', nome: 'CHECKLIST DE HOMOLOGAÇÃO', vencimentoObrigatorio: false },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL', vencimentoObrigatorio: false },
    { id: 'distrato', nome: 'Distrato', vencimentoObrigatorio: false },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Prática de mercado', lembreteDias: 3 },
    { id: 'registro-treinamento', nome: 'REGISTRO DE TREINAMENTO', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Prática de mercado', lembreteDias: 3 },
    { id: 'sintegra', nome: 'SINTEGRA', vencimentoObrigatorio: false }
  ],
  'BASE COLIGADA - TR': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Código de Posturas Municipal', lembreteDias: 3 },
    { id: 'antt', nome: 'ANTT', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Resolução ANTT 3.056/09', lembreteDias: 3 },
    { id: 'apolice-seguros', nome: 'APÓLICE DE SEGUROS', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Vigência da apólice', lembreteDias: 3 },
    { id: 'avcb', nome: 'AVCB', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Decreto Estadual (ex: SP: 63.911/18)', lembreteDias: 3 },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ', vencimentoObrigatorio: false },
    { id: 'checklist-homologacao-base', nome: 'CHECKLIST - HOMOLOGAÇÃO DE BASE', vencimentoObrigatorio: false },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Prática de mercado', lembreteDias: 3 },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL', vencimentoObrigatorio: false },
    { id: 'distrato', nome: 'Distrato', vencimentoObrigatorio: false },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Prática de mercado', lembreteDias: 3 },
    { id: 'performance-mensal', nome: 'PERFORMANCE MENSAL', vencimentoObrigatorio: false },
    { id: 'registro-treinamento', nome: 'REGISTRO DE TREINAMENTO', vencimentoObrigatorio: true, prazoPadrao: 365, referenciaLegal: 'Prática de mercado', lembreteDias: 3 },
    { id: 'sintegra', nome: 'SINTEGRA (INSCRIÇÃO ESTADUAL)', vencimentoObrigatorio: false }
  ],
  'CALIBRAÇÃO DE EQUIPAMENTOS': [
    { id: 'alvara', nome: 'Alvará de Funcionamento.' },
    { id: 'atestado-inmetro', nome: 'Atestado de Autorização - INMETRO.' },
    { id: 'certificado-acreditacao-inmetro', nome: 'Certificado de Acreditação - INMETRO.' },
    { id: 'certificado-acreditacao-cal0281', nome: 'Certificado de Acreditação CAL-0281 - INMETRO.' },
    { id: 'certificado-acreditacao-crl0252', nome: 'Certificado de Acreditação CRL-0252 - INMETRO.' },
    { id: 'clcb', nome: 'Certificado de Licença do Corpo de Bombeiros - CLCB.' },
    { id: 'cnpj-atualizado', nome: 'CNPJ Atualizado (Ativo).' },
    { id: 'contrato-prest-servicos', nome: 'Contrato de Prestação de Serviços.' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'sla-fornecedor-calibracao', nome: 'SLA fornecedor - calibração' }
  ],
  'CLIENTE NATURA - FORNECEDOR DE INSUMO LOGÍSTICO': [
    { id: 'alvara', nome: 'Alvará de Funcionamento.' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'certificacao-iso9001', nome: 'Certificação ISO 9001:2015.' },
    { id: 'certificado-mov-residuos', nome: 'Certificado de Movimentação de Resíduos de Interesse Ambiental' },
    { id: 'cetesb-licenca-operacao', nome: 'CETESB - Licença de Operação.' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'email-cliente-atestando', nome: 'E-MAIL DO CLIENTE ATESTANDO A RESPONSABILIDADE PELO FORNECEDOR.' }
  ],
  'COIFA - SERVIÇO ADMINISTRADO PELO REFEITÓRIO (TERCEIRIZADO) - CDCO': [
    { id: 'asos', nome: 'ASOS' },
    { id: 'avcb-protocolo', nome: 'AVCB/PROTOCOLO' },
    { id: 'cnpj-inscricao-estadual', nome: 'CNPJ/ INSCRIÇÃO ESTADUAL' },
    { id: 'contrato-social-requerimento', nome: 'CONTRATO SOCIAL/ REQUERIMENTO' },
    { id: 'epi', nome: 'EPI' },
    { id: 'ficha-epi', nome: 'FICHA DE EPI' },
    { id: 'ficha-registro', nome: 'FICHA DE REGISTRO' },
    { id: 'fispq-produto', nome: 'FISPQ DO PRODUTO' },
    { id: 'licenca-protocolo', nome: 'LICENÇA/PROTOCOLO' },
    { id: 'nr35', nome: 'NR 35' },
    { id: 'pt', nome: 'PT' },
    { id: 'treinamento-fispq', nome: 'TREINAMENTO DE TRABALHO E FISPQ' }
  ],
  'COLETA de ÓLEO (ADMINISTRADO PELA EMPRESA TERCEIRIZADA DO REFEITÓRIO) - CDCO': [
    { id: 'avcb', nome: 'AVCB' },
    { id: 'cetesb', nome: 'CETESB' },
    { id: 'comprovante-destinacao-final', nome: 'COMPROVANTE DE DESTINAÇÃO FINAL ÓLEO' },
    { id: 'contrato-fornecimento-oleo', nome: 'CONTRATO DE FORNECIMENTO DE ÓLEO (Entre a Preserva e a empresa terceirizada do refeitório)' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'ctf-ibama', nome: 'CTF IBAMA' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'licenca-funcionamento', nome: 'LICENÇA DE FUNCIONAMENTO' }
  ],
  'CONTROLE AMBIENTAL': [
    { id: '43', nome: 'Alvará de Funcionamento.' },
    { id: '44', nome: 'Apólice de Seguros.' },
    { id: '45', nome: 'Certificado de Associado - ASSOCIAÇÃO DOS CONTROLADORES DE VETORES E PRAGAS URBANAS.' },
    { id: '46', nome: 'Certificados de Aprovação (CA) EPI em geral' },
    { id: '47', nome: 'CERTIFICADO DE TREINAMENTO - JENESSON DO NASCIMENTO FLORENTINO' },
    { id: '48', nome: 'CNPJ.' },
    { id: '49', nome: 'Contrato de Prestação de Serviços.' },
    { id: '50', nome: 'Cronograma Anual de Aplicação - Cotia' },
    { id: '51', nome: 'Declaração de Reciclagem/Destinação Final.' },
    { id: '52', nome: 'Licença de Funcionamento SIVISA' },
    { id: '53', nome: 'Mapa de Iscas' },
    { id: '55', nome: 'PCMSO.' },
    { id: '56', nome: 'PPRA.' },
    { id: '57', nome: 'Termo de Responsabilidade Técnica.' }
  ],
  'CONTROLE DE PONTO': [
    { id: 'avcb', nome: 'AVCB' },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'licenca-funcionamento', nome: 'LICENÇA DE FUNCIONAMENTO' },
    { id: 'politica-privacidade', nome: 'POLÍTICA DE PRIVACIDADE' }
  ],
  'DESENTUPIDOR SANITÁRIO': [
    { id: 'alvara', nome: 'Alvará de Funcionamento.' },
    { id: 'cetesb-operacao', nome: 'CETESB - Licença de Operação.' },
    { id: 'cetesb-previa', nome: 'CETESB - Licença Prévia e de Instalação.' },
    { id: 'cnpj-atualizado', nome: 'CNPJ Atualizado.' },
    { id: 'contrato-social', nome: 'Contrato Social.' },
    { id: 'remessa-efluentes', nome: 'Remessa de Efluentes.' }
  ],
  'DIVERSOS': [
    { id: 'fernanda-vieira', nome: '23.384.723 FERNANDA VIEIRA DOS SANTOS' },
    { id: 'aprovacao-qualidade', nome: 'APROVAÇÃO QUALIDADE' },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ' },
    { id: 'cnpj', nome: 'CNPJ' },
    { id: 'comprovante-inscricao', nome: 'Comprovante de Inscrição e de Situação Cadastral' },
    { id: 'comprovante-inscricao-2', nome: 'COMPROVANTE DE INSCRIÇÃO E DE SITUAÇÃOCADASTRAL' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-athena', nome: 'CONTRATO ATHENA SECURITY - FIREWALL POSTALL - SEGURANÇA DA INFORMAÇÃO' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-prest-serv-2', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇOS' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'declaracao', nome: 'DECLARAÇÃO' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'doc-colaboradores', nome: 'DOCUMENTAÇÃO COLABORADORES' },
    { id: 'doc-fornecedor-dest-final', nome: 'DOCUMENTAÇÃO FORNECEDOR DESTINAÇÃO FINAL' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'ficha-cadastral-contrato-social', nome: 'FICHA CADASTRAL E CONTRATO SOCIAL' },
    { id: 'homologar-fornecedor', nome: 'Homologar Fornecedor?' },
    { id: 'pcmso', nome: 'PCMSO' },
    { id: 'ppra', nome: 'PPRA' },
    { id: 'regimento-senai', nome: 'REGIMENTO SENAI' },
    { id: 'registro-crc', nome: 'REGISTRO CRC' },
    { id: 'validacao-qualidade', nome: 'Validação da Qualidade' },
    { id: 'validacao-qualidade-2', nome: 'VALIDAÇÃO QUALIDADE' },
    { id: 'validacao-qualidade-3', nome: 'VALIDAÇÃO QUALIDADE.' }
  ],
  'DOCUMENTAÇÃO LEGAL - FILIAL (CDBD)': [
    { id: 'avcb', nome: 'AVCB' },
    { id: 'certidao-regularidade-cr', nome: 'CERTIDÃO DE REGULARIDADE - CR' },
    { id: 'certidao-uso-solo', nome: 'CERTIDÃO DE USO DO SOLO' },
    { id: 'certificado-mangueira', nome: 'CERTIFICADO DE INSPEÇÃO E MANUTENÇÃO EM MANGUEIRA DE INCÊNDIO' },
    { id: 'certificado-limpeza-caixa', nome: 'CERTIFICADO DE LIMPEZA DE CAIXA D\'ÁGUA' },
    { id: 'cetesb-isencao', nome: 'CETESB - DECLARAÇÃO DE ISENÇÃO' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-locacao', nome: 'CONTRATO DE LOCAÇÃO' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'habite-se', nome: 'HABITE-SE' },
    { id: 'iptu', nome: 'IPTU' },
    { id: 'laudo-potabilidade', nome: 'LAUDO DE POTABILIDADE DA ÁGUA' },
    { id: 'laudo-spda', nome: 'LAUDO SPDA' },
    { id: 'licenca-funcionamento-anvisa', nome: 'LICENÇA DE FUNCIONAMENTO ANVISA' },
    { id: 'licenca-funcionamento-alvara', nome: 'LICENÇA DE FUNCIONAMENTO/ALVARÁ' },
    { id: 'pcmso', nome: 'PCMSO' },
    { id: 'pgr', nome: 'PGR' },
    { id: 'relatorio-manut-extintores', nome: 'RELATÓRIO DE MANUTENÇÃO EM EXTINTORES' },
    { id: 'relatorio-instalacoes-eletricas', nome: 'RELATÓRIO E ATESTADO DAS INSTALAÇÕES ELÉTRICAS' },
    { id: 'simulado-abandono', nome: 'SIMULADO DE ABANDONO - BRIGADA DE INCÊNDIO' }
  ],
  'DOCUMENTAÇÃO LEGAL - FILIAL (CDJD)': [
    { id: 'apolice-seguros', nome: 'APÓLICE DE SEGUROS' },
    { id: 'art-bertolini', nome: 'ART BERTOLINI' },
    { id: 'art-quimica', nome: 'ART QUÍMICA' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'certidao-regularidade-cr', nome: 'CERTIDÃO DE REGULARIDADE - CR' },
    { id: 'certidao-uso-solo', nome: 'CERTIDÃO DE USO DO SOLO' },
    { id: 'certificado-mangueira', nome: 'CERTIFICADO DE INSPEÇÃO E MANUTENÇÃO EM MANGUEIRA DE INCÊNDIO' },
    { id: 'certificado-limpeza-caixa', nome: 'CERTIFICADO DE LIMPEZA DE CAIXA D\'ÁGUA' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-locacao', nome: 'CONTRATO DE LOCAÇÃO' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'habite-se', nome: 'HABITE-SE' },
    { id: 'iptu', nome: 'IPTU' },
    { id: 'laudo-potabilidade', nome: 'LAUDO DE POTABILIDADE DA ÁGUA' },
    { id: 'laudo-spda', nome: 'LAUDO SPDA' },
    { id: 'licenca-cetesb', nome: 'LICENÇA CETESB' },
    { id: 'licenca-funcionamento-anvisa', nome: 'LICENÇA DE FUNCIONAMENTO ANVISA' },
    { id: 'licenca-funcionamento-alvara', nome: 'LICENÇA DE FUNCIONAMENTO/ALVARÁ' },
    { id: 'memorial-atividade', nome: 'MEMORIAL DE ATIVIDADE' },
    { id: 'memorial-descritivo', nome: 'MEMORIAL DESCRITIVO' },
    { id: 'outorga-protocolo', nome: 'Outorga - Protocolo de Substituição da Titularidade' },
    { id: 'outorga-poco', nome: 'OUTORGA POÇO' },
    { id: 'pcmso', nome: 'PCMSO' },
    { id: 'pgr', nome: 'PGR' },
    { id: 'relatorio-manut-extintores', nome: 'RELATÓRIO DE MANUTENÇÃO EM EXTINTORES' },
    { id: 'relatorio-instalacoes-eletricas', nome: 'RELATÓRIO E ATESTADO DAS INSTALAÇÕES ELÉTRICAS' },
    { id: 'relatorio-abrangencia-gerador', nome: 'RELATÓRIO E ATESTADO DE ABRANGÊNCIA DO GRUPO MOTO GERADOR' },
    { id: 'simulado-abandono', nome: 'SIMULADO DE ABANDONO - BRIGADA DE INCÊNDIO' }
  ],
  'DOCUMENTAÇÃO LEGAL - FILIAL (CDVG)': [
    { id: 'afe-correlatos', nome: 'AFE CORRELATOS E SANEANTES' },
    { id: 'afe-cosmeticos', nome: 'AFE COSMÉTICOS' },
    { id: 'afe-medicamentos', nome: 'AFE MEDICAMENTOS' },
    { id: 'alvara', nome: 'Alvará de Funcionamento.' },
    { id: 'art', nome: 'Anotação de Responsabilidade Técnica - ART' },
    { id: 'antt', nome: 'ANTT - Agência Nacional Transporte Terrestre - Matriz' },
    { id: 'apolice-seguros', nome: 'APÓLICE DE SEGUROS' },
    { id: 'avcb', nome: 'AVCB (Auto de Vistoria do Corpo de Bombeiros).' },
    { id: 'baixa-rt', nome: 'Baixa de Responsabilidade Técnica.' },
    { id: 'baixa-crf', nome: 'BAIXA DO CRF - RODRIGO' },
    { id: 'carteira-farmaceutico', nome: 'Carteira de Identidade Profissional do Farmacêutico.' },
    { id: 'certidao-regularidade-crf', nome: 'CERTIDÃO DE REGULARIDADE - CRF' },
    { id: 'certificado-compensacao', nome: 'CERTIFICADO DE COMPENSAÇÃO' },
    { id: 'certificado-limpeza-caixa', nome: 'CERTIFICADO DE LIMPEZA DA CAIXA D\'ÁGUA' },
    { id: 'certificado-iso', nome: 'CERTIFICADO ISO 9001:2015' },
    { id: 'certificado-iso-postall', nome: 'CERTIFICADO ISO 9001:2015 - POSTALL CARGAS' },
    { id: 'cnpj-atualizado', nome: 'CNPJ Atualizado.' },
    { id: 'cnpj-postall-matriz', nome: 'CNPJ POSTALL CARGAS (MATRIZ)' },
    { id: 'cnpj-postall-filial', nome: 'CNPJ POSTALL TRANSPORTE (FILIAL)' },
    { id: 'crf-anual', nome: 'Conselho Regional de Farmácia  - CRF Anual.' },
    { id: 'contrato-social-postall', nome: 'Contrato Social Postall.' },
    { id: 'declaracao-nao-medicamentos', nome: 'DECLARAÇÃO DE NÃO ARMAZENAMENTO E TRANSPORTE DE MEDICAMENTOS' },
    { id: 'declaracao-veiculos-anvisa', nome: 'DECLARAÇÃO VEÍCULOS ANVISA' },
    { id: 'ficha-cadastral-prefeitura', nome: 'Ficha Cadastral na Prefeitura.' },
    { id: 'ficha-cadastral-postall', nome: 'Ficha Cadastral PostALL.' },
    { id: 'ficha-cadastral', nome: 'Ficha Cadastral.' },
    { id: 'habite-se', nome: 'HABITE-SE' },
    { id: 'inscricao-estadual', nome: 'INSCRIÇÃO ESTADUAL' },
    { id: 'iptu', nome: 'IPTU' },
    { id: 'laudo-termografico', nome: 'Laudo de Inspeção Termográfica (instalações elétricas)' },
    { id: 'laudo-potabilidade', nome: 'LAUDO DE POTABILIDADE DA ÁGUA' },
    { id: 'laudo-spda', nome: 'LAUDO SPDA (NR 10)' },
    { id: 'licenca-anvisa', nome: 'LICENÇA DE FUNCIONAMENTO ANVISA' },
    { id: 'licenca-instalacao', nome: 'LICENÇA DE INSTALAÇÃO' },
    { id: 'licenca-operacao', nome: 'LICENÇA DE OPERAÇÃO' },
    { id: 'organograma-postall', nome: 'ORGANOGRAMA POSTALL' },
    { id: 'outorga-poco', nome: 'OUTORGA POÇO' },
    { id: 'pcmso', nome: 'PCMSO' },
    { id: 'pgr', nome: 'PGR' },
    { id: 'registro-acervo', nome: 'Registro de Contrato de Acervo Técnico sob forma de Anotação de Responsabilidade Técnica - Lei Federal 6496/77 Conselho Regional de Engenharia e Agronomia do RS.' },
    { id: 'relatorio-mangueiras', nome: 'RELATÓRIO DE MANGUEIRAS' },
    { id: 'relatorio-manut-extintores', nome: 'RELATÓRIO DE MANUTENÇÃO EM EXTINTORES' },
    { id: 'selo-tesouro-verde', nome: 'SELO TESOURO VERDE' },
    { id: 'simulado-abandono', nome: 'SIMULADO DE ABANDONO - BRIGADA DE INCÊNDIO' },
    { id: 'utilizacao-marca', nome: 'UTILIZAÇÃO MARCA - AUTORIZAÇÃO VANZOLINI' }
  ],
  'DOCUMENTAÇÃO LEGAL - MATRIZ (CDCO)': [
    { id: 'afe-cosmeticos', nome: 'AFE - Cosméticos/Perfumes/Prod. Higiene' },
    { id: 'afe-medicamento', nome: 'AFE - Medicamento.' },
    { id: 'afe-saneante', nome: 'AFE - Saneante Domis.' },
    { id: 'alvara-cdvg', nome: 'Alvará de Funcionamento (CD VG)' },
    { id: 'alvara-sivisa', nome: 'Alvará de Funcionamento SIVISA - CDVG' },
    { id: 'alvara-habite-se', nome: 'Alvará de Habite-se.' },
    { id: 'antt', nome: 'ANTT (Agência Nacional de Transportes Terrestres).' },
    { id: 'apolice-seguros', nome: 'APÓLICE DE SEGUROS' },
    { id: 'apolice-seguros-frota', nome: 'APÓLICE DE SEGUROS DA FROTA' },
    { id: 'art-obra', nome: 'ART de Obra ou Serviço.' },
    { id: 'avcb', nome: 'AVCB (Auto de Vistoria do Corpo de Bombeiro).' },
    { id: 'avcb-cdvg', nome: 'AVCB CDVG' },
    { id: 'baixa-crf', nome: 'BAIXA DO CRF - RODRIGO' },
    { id: 'baixa-vigilancia-cotia', nome: 'Baixa na Vigilância Sanitária de Cotia – Rodney Bueres (RT – G1)' },
    { id: 'carteira-farmaceutico', nome: 'Carteira de Identidade Profissional Farmacêutico/RG.' },
    { id: 'certidao-diretrizes', nome: 'Certidão de Diretrizes Uso e Ocupação do Solo.' },
    { id: 'certidao-regularidade-crf', nome: 'CERTIDÃO DE REGULARIDADE - CRF' },
    { id: 'certificado-mangueira', nome: 'CERTIFICADO DE INSPEÇÃO E MANUTENÇÃO EM MANGUEIRA DE INCÊNDIO' },
    { id: 'certificado-limpeza-caixa', nome: 'CERTIFICADO DE LIMPEZA DA CAIXA D\'ÁGUA' },
    { id: 'certificado-iso', nome: 'CERTIFICADO ISO 9001:2015' },
    { id: 'certificado-iso-postall', nome: 'CERTIFICADO ISO 9001:2015 - POSTALL CARGAS' },
    { id: 'cnpj-postall-filial', nome: 'CNPJ POSTALL CARGAS (FILIAL)' },
    { id: 'cnpj-postall-matriz', nome: 'CNPJ POSTALL TRANSPORTE (MATRIZ)' },
    { id: 'comunique-se', nome: 'Comunique-se.' },
    { id: 'consulta-anvisa', nome: 'Consulta - Agência Nacional de Vigilância Sanitária' },
    { id: 'contrato-prest-supp', nome: 'Contrato de Prestação de Serviços - SUPPORTE.' },
    { id: 'contrato-social-jucesp', nome: 'Contrato Social - JUCESP.' },
    { id: 'contrato-social-penna', nome: 'CONTRATO SOCIAL PENNA INVESTIMENTOS' },
    { id: 'datavisa', nome: 'DATAVISA - Assunção de Responsabilidade Técnica.' },
    { id: 'declaracao-atividade-isenta', nome: 'Declaração de Atividade Isenta de Licenciamento.' },
    { id: 'declaracao-veiculos-anvisa', nome: 'DECLARAÇÃO VEÍCULOS ANVISA' },
    { id: 'ficha-cadastral-jucesp', nome: 'Ficha Cadastral Completa JUCESP.' },
    { id: 'ficha-cadastral-prefeitura', nome: 'Ficha Cadastral Completa Prefeitura.' },
    { id: 'ficha-cadastral', nome: 'Ficha Cadastral.' },
    { id: 'habite-se', nome: 'HABITE-SE' },
    { id: 'iptu', nome: 'IPTU' },
    { id: 'laudo-potabilidade', nome: 'LAUDO DE POTABILIDADE DA ÁGUA' },
    { id: 'laudo-potabilidade-cdvg', nome: 'Laudo de Potabilidade da Água - CDVG' },
    { id: 'laudo-instalacoes-eletricas', nome: 'LAUDO DE VISTORIA DAS INSTALAÇÕES ELÉTRICAS' },
    { id: 'laudo-spda', nome: 'LAUDO SPDA (NR 10)' },
    { id: 'laudo-tecnico-coifa', nome: 'LAUDO TÉCNICO - LIMPEZA DO SISTEMA DE EXAUSTÃO (COIFA)' },
    { id: 'laudo-tecnico-avaliacao', nome: 'Laudo Técnico de Avaliação - LTA.' },
    { id: 'licenca-funcionamento', nome: 'LICENÇA DE FUNCIONAMENTO' },
    { id: 'licenca-funcionamento-sivisa', nome: 'Licença de Funcionamento - Sistema de Informação em Vigilância Sanitária' },
    { id: 'licenca-funcionamento-refeitorio', nome: 'LICENÇA DE FUNCIONAMENTO - VIGILÂNCIA SANITÁRIA REFEITÓRIO' },
    { id: 'licenciamento-veiculo-dta7066', nome: 'Licenciamento Veículo - DTA7066.' },
    { id: 'licenciamento-veiculo-dte5031', nome: 'Licenciamento Veículo - DTE5031.' },
    { id: 'licenciamento-veiculo-elw9949', nome: 'Licenciamento Veículo - ELW9949.' },
    { id: 'licenciamento-veiculo-ewj7488', nome: 'Licenciamento Veículo - EWJ7488.' },
    { id: 'licenciamento-veiculo-fdb1240', nome: 'Licenciamento Veículo - FDB1240.' },
    { id: 'licenciamento-veiculo-fdb1246', nome: 'Licenciamento Veículo - FDB1246.' },
    { id: 'licenciamento-veiculo-fdb1271', nome: 'Licenciamento Veículo - FDB1271.' },
    { id: 'licenciamento-veiculo-fsb2263', nome: 'Licenciamento Veículo - FSB2263.' },
    { id: 'licenciamento-veiculo-gcq1173', nome: 'Licenciamento Veículo - GCQ1173.' },
    { id: 'licenciamento-veiculo-gcq1718', nome: 'Licenciamento Veículo - GCQ1718.' },
    { id: 'licenciamento-veiculo-ggj1173', nome: 'Licenciamento Veículo - GGJ1173.' },
    { id: 'lta-cdco', nome: 'LTA - CDCO G1 - PACTUALL' },
    { id: 'matricula-cotia', nome: 'Matrícula - Registro de Imóveis de Cotia.' },
    { id: 'memorial-calculo', nome: 'Memorial de Cálculo - TARGET.' },
    { id: 'memorial-servicos', nome: 'Memorial de Serviços - TARGET.' },
    { id: 'memorial-descritivo', nome: 'Memorial Descritivo - TARGET.' },
    { id: 'organograma-postall', nome: 'ORGANOGRAMA POSTALL' },
    { id: 'pcmso', nome: 'PCMSO' },
    { id: 'pgr', nome: 'PGR' },
    { id: 'politica-integrada', nome: 'Política Integrada do Sistema de Gestão da Qualidade.' },
    { id: 'processo-regularizacao', nome: 'Processo de Regularização Galpão 2.' },
    { id: 'projeto-completo', nome: 'Projeto Completo.' },
    { id: 'proposta-tecnica-onira', nome: 'Proposta Técnica - Onira.' },
    { id: 'relatorio-manut-extintores', nome: 'RELATÓRIO DE MANUTENÇÃO EM EXTINTORES' },
    { id: 'registro-responsabilidade', nome: 'Resgistro de Responsabilidade Técnica.' },
    { id: 'simulado-abandono', nome: 'SIMULADO DE ABANDONO - BRIGADA DE INCÊNDIO' },
    { id: 'utilizacao-marca', nome: 'UTILIZAÇÃO MARCA - AUTORIZAÇÃO VANZOLINI' }
  ],
  'EMPRESA CERTIFICADORA': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ' },
    { id: 'certificado-habilidade-tecnica', nome: 'CERTIFICADO DE HABILIDADE TÉCNICA' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-prest-serv-proposta-tecnica', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO/PROPOSTA TÉCNICA' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' }
  ],
  'EMPRESA ESTATAL': [
    { id: 'cnpj', nome: 'CNPJ' },
    { id: 'comprovante-inscricao', nome: 'Comprovante de Inscrição e de Situação Cadastral' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-uso-sistema', nome: 'CONTRATO DE USO DO SISTEMA DE DISTRIBUIÇÃO' }
  ],
  'ENGENHARIA E CONSTRUÇÃO': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO' },
    { id: 'alvara2', nome: 'Alvará de Funcionamento.' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'avcb2', nome: 'AVCB.' },
    { id: 'carteira-identidade-rt', nome: 'CARTEIRA DE IDENTIDADE DO RESPONSÁVEL TÉCNICO' },
    { id: 'carteira-identidade-crea', nome: 'Carteira de Identidade Responsável Técnico - CREA SP' },
    { id: 'cnpj-atualizado', nome: 'CNPJ Atualizado (Ativo).' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-prest-serv2', nome: 'Contrato de Prestação de Serviços.' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'proposta-comercial', nome: 'Proposta comercial' }
  ],
  'ERGONOMIA E GINASTICA LABORAL': [
    { id: 'ccmei', nome: 'CERTIFICADO DE CONDIÇÃO DE MICRO EMPREENDEDOR INDIVIDUAL (CCMEI)' },
    { id: 'certificados-especializacoes', nome: 'CERTIFICADOS DAS ESPECIALIZAÇÕES PARA REALIZAÇÕES DAS ATIVIDADES PROFISSIONAIS (FACULDADES, CURSOS E ETC.)' },
    { id: 'comprovante-endereco', nome: 'COMPROVANTE DE ENDEREÇO' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'cpf', nome: 'CPF' },
    { id: 'cref', nome: 'CREF' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'rg', nome: 'RG' }
  ],
  'ESCRITÓRIO DE CONTABILIDADE': [
    { id: 'avcb', nome: 'AVCB' },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'licenca-funcionamento', nome: 'LICENÇA DE FUNCIONAMENTO' }
  ],
  'ETC - EMPRESA DE TRANSPORTE RODOVIÁRIO DE CARGAS': [
    { id: 'antt', nome: 'ANTT' },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ' },
    { id: 'cnh-motorista', nome: 'CNH DO MOTORISTA' },
    { id: 'comprovante-endereco', nome: 'COMPROVANTE DE ENDEREÇO' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'resultado-pancary', nome: 'RESULTADO DA PESQUISA PANCARY' }
  ],
  'FABRICANTE DE CADEIRA': [
    { id: 'cnpj', nome: 'CNPJ' },
    { id: 'contrato-social', nome: 'Contrato Social' }
  ],
  'FILIAL': [
    { id: 'avcb', nome: 'AVCB' },
    { id: 'cnpj', nome: 'CNPJ' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'licenca-funcionamento', nome: 'LICENÇA DE FUNCIONAMENTO' },
    { id: 'licenca-funcionamento-anvisa', nome: 'LICENÇA DE FUNCIONAMENTO ANVISA' },
    { id: 'mapa', nome: 'MAPA' },
    { id: 'sintegra', nome: 'SINTEGRA' }
  ],
  'FORNECEDOR DE INSUMOS LOGÍSTICOS': [
    { id: 'alvara', nome: 'Alvará de Funcionamento.' },
    { id: 'avcb', nome: 'AVCB.' },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ' },
    { id: 'certificacao-iso9001', nome: 'Certificação ISO 9001:2015.' },
    { id: 'certificado-destinacao-final', nome: 'CERTIFICADO DE DESTINAÇÃO FINAL' },
    { id: 'certificado-mov-residuos', nome: 'Certificado de Movimentação de Resíduos de Interesse Ambiental.' },
    { id: 'certificado-fsc', nome: 'CERTIFICADO FSC' },
    { id: 'cetesb-licenca-operacao', nome: 'CETESB - LICENÇA DE OPERAÇÃO.' },
    { id: 'cnpj', nome: 'CNPJ' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'comprovante-inscricao-ibama', nome: 'COMPROVANTE DE INSCRIÇÃO IBAMA' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'programa-sustentabilidade', nome: 'PROGRAMA DE SUSTENTABILIDADE.' },
    { id: 'sintegra', nome: 'SINTEGRA (INSCRIÇÃO ESTADUAL)' }
  ],
  'FORNECEDOR DE UNIFORMES': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' }
  ],
  'FROTA AGREGADA': [
    { id: 'antt', nome: 'ANTT' },
    { id: 'cnh', nome: 'CNH' },
    { id: 'cnh-veiculo-agregado', nome: 'CNH - CARTEIRA DE HABILITAÇÃO PERTINENTE AO VEICULO AGREGADO.' },
    { id: 'comprovante-endereco', nome: 'COMPROVANTE DE ENDEREÇO' },
    { id: 'crlv', nome: 'CRLV' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'documentacao-veiculo', nome: 'DOCUMENTAÇÃO VEÍCULO' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'ficha-cadastral-financeiro', nome: 'FICHA CADASTRAL - FINANCEIRO' },
    { id: 'licenciamento-veiculo', nome: 'LICENCIAMENTO DO VEÍCULO' },
    { id: 'pesquisa-agregado', nome: 'PESQUISA "AGREGADO"' },
    { id: 'pesquisa-pamcary', nome: 'PESQUISA "PANCARY"' },
    { id: 'pesquisa-pancary2', nome: 'PESQUISA PANCARY' }
  ],
  'FUNCIONÁRIO - OP': [
    { id: 'antt', nome: 'ANTT' },
    { id: 'aprovacao-qualidade', nome: 'APROVAÇÃO QUALIDADE' },
    { id: 'cnh', nome: 'CNH' },
    { id: 'comprovante-residencia', nome: 'Comprovante de residência' },
    { id: 'crlv', nome: 'CRLV' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'ficha-cadastral', nome: 'Ficha cadastral' },
    { id: 'pesquisa-pamcary', nome: 'Pesquisa "Pamcary"' },
    { id: 'validacao-qualidade', nome: 'VALIDAÇÃO QUALIDADE' }
  ],
  'GÁS - EMPRESA TERCEIRIZADA PELO REFEITÓRIO (GESTÃO TERCEIRIZADA) - CDCO': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ' },
    { id: 'certificado-treinamento', nome: 'CERTIFICADO DE TREINAMENTO (AOS COLABORADORES QUE FOREM PRESTAR SERVIÇOS A POSTALL)' },
    { id: 'consulta-sintegra', nome: 'CONSULTA SINTEGRA' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'licenca-operacao', nome: 'LICENÇA DE OPERAÇÃO' },
    { id: 'periculosidade', nome: 'PERICULOSIDADE' },
    { id: 'registro-rt', nome: 'REGISTRO DE RESPONSABILIDADE TÉCNICA' }
  ],
  'LIMPEZA - SERVIÇO TERCEIRIZADO': [
    { id: 'alvara', nome: 'Alvará de Funcionamento' },
    { id: 'avcb', nome: 'AVCB (Auto de Vistoria do Corpo de Bombeiros)' },
    { id: 'certidao-negativa-estadual', nome: 'Certidões negativas de débitos  Estaduais' },
    { id: 'certidao-negativa-municipal', nome: 'Certidões negativas de débitos  Municipais' },
    { id: 'certidao-negativa-federal', nome: 'Certidões negativas de débitos e Federais' },
    { id: 'cetesb-ou-isenta', nome: 'CETESB  ou declaração de isenta' },
    { id: 'cnd-fgts', nome: 'CND - FGTS' },
    { id: 'cnd-inss', nome: 'CND - INSS ' },
    { id: 'contrato-prest-serv-postall', nome: 'Contrato de Prestação de Serviços com a Postall' },
    { id: 'contrato-social', nome: 'Contrato Social ' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'ficha-cadastral', nome: 'Ficha Cadastral' },
    { id: 'fispq', nome: 'FISPQs dos produtos autorizados ' },
    { id: 'manuais', nome: 'MANUAIS' },
    { id: 'pop-its', nome: 'POP\'S E ITS DE BOAS PRÁTICAS' },
    { id: 'relatorio-limpeza', nome: 'Relatório de limpeza' },
    { id: 'sla-pesquisa', nome: 'SLA ou Pesquisa de satisfação referente a prestação de serviço realizada  ' },
    { id: 'treinamento-pragas', nome: 'Treinamento Controle de Pragas da equipe' },
    { id: 'treinamento-boas-praticas', nome: 'Treinamento de Boas Práticas da Equipe' }
  ],
  'Locação de Suco': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'cnpj', nome: 'CNPJ' },
    { id: 'contrato-locacao', nome: 'CONTRATO DE LOCAÇÃO' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'inscricao-estadual', nome: 'INSCRIÇÃO ESTADUAL' },
    { id: 'sintegra', nome: 'SINTEGRA' }
  ],
  'LOCADORA DE GALPÕES': [
    { id: 'avcb', nome: 'AVCB' },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-locacao', nome: 'CONTRATO DE LOCAÇÃO' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'licenca-funcionamento', nome: 'LICENÇA DE FUNCIONAMENTO' },
    { id: 'manutencao-bombas', nome: 'MANUTENÇÃO PERIÓDICA CASA DE BOMBAS' },
    { id: 'regulamento-patria', nome: 'REGULAMENTO PATRIA' }
  ],
  'MANUTENÇÃO DE GERADORES': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO' },
    { id: 'aso', nome: 'ASO' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'crea', nome: 'CREA' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'nr10', nome: 'NR 10' }
  ],
  'MANUTENÇÃO DE VEICULOS': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO' },
    { id: 'alvara2', nome: 'Alvará de Funcionamento.' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'avcb2', nome: 'AVCB.' },
    { id: 'cnpj-atualizado', nome: 'CNPJ Atualizado (Ativo).' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'contrato-social2', nome: 'Contrato Social.' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'licenca-cetesb', nome: 'Licença CETESB (LI - Licença de Instalação e LO - Licença de Operação).' },
    { id: 'licenca-cetesb-dispensa', nome: 'LICENÇA CETESB (OU DECLARAÇÃO DE DISPENSA)' },
    { id: 'pae', nome: 'PAE - Plano de Atendimento a Emergencias. ' },
    { id: 'registro-treinamento', nome: 'REGISTRO DE TREINAMENTO' }
  ],
  'MÃO DE OBRA TEMPORÁRIA': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO' },
    { id: 'avcb', nome: 'AVCB (Auto de Vistoria do Corpo de Bombeiros)' },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ' },
    { id: 'cnd-trabalhista', nome: 'CND - Certidão Negativa de Débitos Trabalhistas' },
    { id: 'cnd-fgts', nome: 'CND - FGTS - CRF' },
    { id: 'contrato-prest-serv', nome: 'Contrato de Prestação de Serviços.' },
    { id: 'contrato-social', nome: 'Contrato Social ' },
    { id: 'contrato-social-jucesp', nome: 'Contrato Social - JUCESP' },
    { id: 'distrato', nome: 'Distrato' }
  ],
  'NUTRICIONISTA': [
    { id: 'avcb', nome: 'AVCB' },
    { id: 'comprovante-inscricao-cadastral', nome: 'COMPROVANTE DE INSCRIÇÃO E DE SITUAÇÃO CADASTRAL' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇOS' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'documentos-rt', nome: 'DOCUMENTOS RT' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'inscricao-municipal', nome: 'INSCRIÇÃO MUNICIPAL' },
    { id: 'ltcat', nome: 'LTCAT' },
    { id: 'pcmso', nome: 'PCMSO' },
    { id: 'pgr', nome: 'PGR' }
  ],
  'PENSÃO ALIMENTÍCIA': [
    { id: 'certidao-nascimento', nome: 'CERTIDÃO DE NASCIMENTO' }
  ],
  'PESSOA JURÍDICA - PJ': [
    { id: 'baixa-crf', nome: 'BAIXA DO CRF' },
    { id: 'comprovante-endereco', nome: 'COMPROVANTE DE ENDEREÇO' },
    { id: 'comprovante-pj', nome: 'COMPROVANTE DE PESSOA JURÍDICA' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'comprovante-escolaridade', nome: 'CÓPIA DO COMPROVANTE DE ESCOLARIDADE (DIPLOMA, CERTIFICADO, CERTIDÃO, DECLARAÇÃO DE CONCLUSÃO)' },
    { id: 'cpf', nome: 'CPF' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'assinatura-financeiro-diretoria', nome: 'COM ASSINATURA DO FINANCEIRO E DIRETORIA' },
    { id: 'rg', nome: 'RG' }
  ],
  'PMOC - LIMPEZA E MANUTENÇÃO DE AR-CONDICIONADO': [
    { id: 'abnt-nbr', nome: 'ABNT NBR ISO/IEC 17025:2017' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'ca-dos-epi', nome: 'CA DOS EPI' },
    { id: 'certificado-nr10', nome: 'CERTIFICADO NR 10' },
    { id: 'certificado-nr35', nome: 'CERTIFICADO NR 35' },
    { id: 'coleta-ar', nome: 'COLETA DE AMOSTRA DE AR' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-prest-serv-cdco', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO CDCO' },
    { id: 'contrato-prest-serv-cdjd', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO CDJD' },
    { id: 'contrato-prest-serv-cdvg', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO CDVG' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'ficha-controle-epis', nome: 'FICHA DE CONTROLE DOS EPIS' },
    { id: 'fispq-produtos', nome: 'FISPQ PRODUTOS UTILIZADOS' },
    { id: 'laudo-amostra-ar-cdco', nome: 'LAUDO DE AMOSTRA DE AR - CDCO' },
    { id: 'laudo-amostra-ar-cdjd', nome: 'LAUDO DE AMOSTRA DE AR - CDJD' },
    { id: 'laudo-amostra-ar-cdvg', nome: 'LAUDO DE AMOSTRA DE AR - CDVG' },
    { id: 'licenca-funcionamento', nome: 'LICENÇA DE FUNCIONAMENTO' },
    { id: 'pcmso', nome: 'PCMSO' },
    { id: 'pgr', nome: 'PGR' },
    { id: 'pmoc', nome: 'PMOC' },
    { id: 'pmoc-cdco', nome: 'PMOC - CDCO' },
    { id: 'pmoc-cdjd', nome: 'PMOC - CDJD' },
    { id: 'pmoc-cdvg', nome: 'PMOC - CDVG' },
    { id: 'ppra', nome: 'PPRA' },
    { id: 'programa-anual-cdco', nome: 'PROGRAMA ANUAL DE MANUTENÇÃO - CDCO' },
    { id: 'programa-anual-cdvg', nome: 'PROGRAMA ANUAL DE MANUTENÇÃO - CDVG' },
    { id: 'registro-crbio', nome: 'REGISTRO DE RESPONSABILIDADE TÉCNICA - CRBIO' },
    { id: 'registro-crea', nome: 'REGISTRO DE RESPONSABILIDADE TÉCNICA - CREA' },
    { id: 'registro-treinamento', nome: 'REGISTRO DE TREINAMENTO' },
    { id: 'registro-treinamento-pmoc', nome: 'REGISTRO DE TREINAMENTO REFERENTE AO PMOC' }
  ],
  'PORTARIA - SERVIÇOS TERCEIRIZADO': [
    { id: 'alvara', nome: 'Alvará de Funcionamento.' },
    { id: 'cnd-fgts', nome: 'Certidão de Regularidade com Relação ao FGTS (CND - Certidão Negativa de Débitos - Fundo de Garantia do Tempo de Serviço)' },
    { id: 'cnd-trabalhista', nome: 'Certidão de Regularidade com Relação aos Débitos Trabalhistas (CND - Certidão Negativa de Débitos - Fundo de Garantia do Tempo de Serviço).' },
    { id: 'cnd-estadual', nome: 'Certidão de Regularidade Fiscal Estadual (CND Estadual - Certidão Negativa de Débitos).' },
    { id: 'cnd-federal', nome: 'Certidão Negativa de Débitos Relativos aos Tributos Federais e à dívidas Ativas da União (CND).' },
    { id: 'cnpj-atualizado', nome: 'CNPJ Atualizado (Ativo).' },
    { id: 'contrato-prest-serv-cdjd', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO (CDJD)' },
    { id: 'contrato-prest-serv', nome: 'Contrato de Prestação de Serviços.' },
    { id: 'contrato-social', nome: 'Contrato Social.' },
    { id: 'dados-bancarios', nome: 'Dados Conta Bancária.' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'nr35', nome: 'NR 35' },
    { id: 'proposta-comercial-cdjd', nome: 'PROPOSTA COMERCIAL CDJD' }
  ],
  'PRODUÇÃO CINEMATOGRÁFICAS, AUDIOVISUAIS  E PUBLICITÁRIAS': [
    { id: 'cnpj-atualizado', nome: 'CNPJ Atualizado (Ativo).' },
    { id: 'contrato-social', nome: 'Contrato Social.' }
  ],
  'RECICLAGEM E SUSTENTABILIDADE': [
    { id: 'aditivo-contrato', nome: 'Aditivo do Contrato de Prestação de Serviços' },
    { id: 'alvara', nome: 'Alvará de Funcionamento.' },
    { id: 'antt', nome: 'ANTT - Agência Nacional de Transporte Terrestre' },
    { id: 'antt2', nome: 'ANTT - Agência Nacional de Transporte Terrestre.' },
    { id: 'autorizacao-ambiental', nome: 'Autorização Ambiental para o Transporte Interestadual de Produtos Perigosos.' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'certidao-regularidade-cr', nome: 'CERTIDÃO DE REGULARIDADE - CR' },
    { id: 'certidao-regularidade-cr-meioamb', nome: 'Certidão de Regularidade - CR - Meio Ambiente.' },
    { id: 'certidao-regularidade-cr-meioamb2', nome: 'Certidão de Regularidade - CR - Meio Ambiente. ' },
    { id: 'certificado-emergencias', nome: 'CERTIFICADO CONTRATUAL EMERGÊNCIAS QUÍMICAS.' },
    { id: 'certificado-compensacao', nome: 'CERTIFICADO DE COMPENSAÇÃO' },
    { id: 'certificado-mov-residuos', nome: 'CERTIFICADO DE MOVIMENTAÇÃO DE RESÍDUOS DE INTERESSE AMBIENTAL. ' },
    { id: 'certificado-mov-residuos2', nome: 'CERTIFICADO DE MOVIMENTAÇÃO DE RESÍDUOS DE INTERESSE AMBIENTAL. ' },
    { id: 'certificado-regularidade-cr', nome: 'Certificado de Regularidade - CR.' },
    { id: 'certificado-plano-emergencia', nome: 'CERTIFICADO PLANO DE EMERGÊNCIA RESICLEAN AMBIENTAL LTDA.' },
    { id: 'cetesb-operacao', nome: 'CETESB - LICENÇA DE OPERAÇÃO.' },
    { id: 'clcb', nome: 'CLCB' },
    { id: 'clcb2', nome: 'CLCB.' },
    { id: 'cnpj-atualizado', nome: 'CNPJ Atualizado (Ativo).' },
    { id: 'cnpj', nome: 'CNPJ.' },
    { id: 'contrato-forn-oleo', nome: 'Contrato de Fornecimento de Óleo Comestível Usado.' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-prest-serv-reciclabr-resiclean', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO RECICLA BR x RESICLEAN' },
    { id: 'contrato-prest-serv-reciclabr-rgambiental', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO RECICLA BR x RG AMBIENTAL' },
    { id: 'contrato-prest-servs', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇOS' },
    { id: 'contrato-prest-servs2', nome: 'Contrato de Prestação de Serviços.' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'convencao-vigilancia', nome: 'Convenção Vigilância Sanitária' },
    { id: 'convencao-vigilancia2', nome: 'Convenção Vigilância Sanitária.' },
    { id: 'declaracao-asseguracao', nome: 'DECLARAÇÃO DE ASSEGURAÇÃO' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'fluxo-destinacao', nome: 'Fluxo de destinação.' },
    { id: 'licenca-cetesb', nome: 'LICENÇA CETESB' },
    { id: 'licenca-cetesb2', nome: 'Licença CETESB.' },
    { id: 'licenca-operacao', nome: 'LICENÇA DE OPERAÇÃO' },
    { id: 'pgr-rgambiental', nome: 'PGR RG AMBIENTAL TRANSPORTE LTDA' },
    { id: 'pae', nome: 'PLANO DE ATENDIMENTO EMERGENCIAL (PAE)' },
    { id: 'proposta-tecnica', nome: 'Proposta técnica' },
    { id: 'selo-tesouro-verde', nome: 'SELO TESOURO VERDE' }
  ],
  'REFEITÓRIO COTIA': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'certidao-negativa-federal', nome: 'CERTIDÃO NEGATIVA DE DÉBITO FEDERAL' },
    { id: 'certidao-negativa-municipal', nome: 'CERTIDÃO NEGATIVA DE DÉBITO MUNICIPAL' },
    { id: 'certificado-controle-pragas', nome: 'CERTIFICADO DE CONTROLE DE PRAGAS' },
    { id: 'certificado-limpeza-caixa', nome: 'CERTIFICADO DE LIMPEZA DE CAIXA D\'ÁGUA' },
    { id: 'certificado-potabilidade-agua', nome: 'CERTIFICADO DE POTABILIDADE DA ÁGUA' },
    { id: 'certificado-regularidade-vigilancia', nome: 'CERTIFICADO DE REGULARIDADE VIGILÂNCIA SANITÁRIA' },
    { id: 'cnd-estadual', nome: 'CND - ESTADUAL' },
    { id: 'cnd-fgts', nome: 'CND - FGTS' },
    { id: 'cnd-inss', nome: 'CND - INSS' },
    { id: 'cnpj', nome: 'CNPJ' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-rt', nome: 'CONTRATO RT' },
    { id: 'crn-certidao', nome: 'CRN - CERTIDÃO DE REGULARIDADE DA NUTRICIONISTA RESPONSÁVEL' },
    { id: 'pops-its-manuais', nome: 'POPs, ITs E MANUAIS' },
    { id: 'registro-treinamento', nome: 'REGISTRO DE TREINAMENTO DE BOAS PRATICAS DA EQUIPE OPERACIONAL' },
    { id: 'sla-pesquisa', nome: 'SLA/Pesquisa de Satisfação' }
  ],
  'REFEITÓRIO DE CDVG (Gestão Terceirizada)': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'certidao-negativa-municipal', nome: 'Certidões negativas de débitos  municipais ' },
    { id: 'certidao-negativa-federal', nome: 'Certidões negativas de débitos federaL ' },
    { id: 'certificado-controle-pragas', nome: 'CERTIFICADO DE CONTROLE DE PRAGAS' },
    { id: 'certificado-limpeza-caixa', nome: 'CERTIFICADO DE LIMPEZA DE CAIXA D\'ÁGUA' },
    { id: 'certificado-potabilidade-agua', nome: 'CERTIFICADO DE POTABILIDADE DE ÁGUA' },
    { id: 'certificado-regularidade-vigilancia', nome: 'CERTIFICADO DE REGULARIDADE VIGILÂNCIA SANITÁRIA' },
    { id: 'cnd-estadual', nome: 'CND - ESTADUAL ' },
    { id: 'cnd-fgts', nome: 'CND - FGTS' },
    { id: 'cnd-inss', nome: 'CND - INSS ' },
    { id: 'cnpj', nome: 'CNPJ' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-rt', nome: 'CONTRATO RT' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'crn-certidao', nome: 'CRN -CERTIDÃO DE REGULARIDADE DA NUTRICIONISTA RESPONSÁVEL ' },
    { id: 'licenca-funcionamento', nome: 'LICENÇA DE FUNCIONAMENTO' },
    { id: 'manuais', nome: 'MANUAIS' },
    { id: 'pops-its-manuais', nome: 'POP\'S E ITS DE BOAS PRÁTICAS' },
    { id: 'pops-its-manuais2', nome: 'POPs, ITs E MANUAIS' },
    { id: 'registro-treinamento', nome: 'REGISTRO DE TREINAMENTO DE BOAS PRÁTICAS DA EQUIPE OPERACIONAL' },
    { id: 'sla-pesquisa', nome: 'SLA/Pesquisa de Satisfação' },
    { id: 'termo-aditivo-cafe', nome: 'TERMO ADITIVO CAFÉ DA MANHÃ' },
    { id: 'validacao-qualidade', nome: 'Validação da Qualidade' }
  ],
  'SEGURADORA': [
    { id: 'apolice-seguros', nome: 'APÓLICE DE SEGUROS' },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'distrato', nome: 'Distrato' }
  ],
  'SEGURANÇA TECNOLÓGICA': [
    { id: 'cnpj', nome: 'CNPJ' },
    { id: 'contrato-prest-serv-postall', nome: 'Contrato de Prestação de Serviços com a Postall' },
    { id: 'contrato-social', nome: 'Contrato Social ' }
  ],
  'SERVIÇOS E SOLUÇÕES AMBIENTAIS - REGULARIZAÇÃO': [
    { id: 'cnd-estadual', nome: 'CND - ESTADUAL' },
    { id: 'cnd-federal', nome: 'CND - FEDERAL' },
    { id: 'cnd-fgts', nome: 'CND - FGTS' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'crea-responsavel', nome: 'CREA DO RESPONSÁVEL TÉCNICO' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'proc-certidao-diretrizes', nome: 'Procuração - Certidão de Diretrizes.' },
    { id: 'proc-solicitacao-ambiental', nome: 'Procuração - Solicitação de Manifestação de Ambiental.' },
    { id: 'proposta-comercial-bomba', nome: 'PROPOSTA COMERCIAL INSTALAÇÃO BOMBA DE INCÊNDIO E RECALQUE' },
    { id: 'proposta-comercial-avcb', nome: 'PROPOSTA COMERCIAL RENOVAÇÃO AVCB CDCO' },
    { id: 'proposta-regularizacao', nome: 'Proposta de Regularização.' },
    { id: 'referencias-comerciais', nome: 'REFERENCIAS COMERCIAIS' },
    { id: 'sintegra', nome: 'SINTEGRA' }
  ],
  'TAC - TRANSPORTADOR AUTÔNOMO DE CARGAS': [
    { id: 'antt', nome: 'ANTT' },
    { id: 'cnh-motorista', nome: 'CNH DO MOTORISTA' },
    { id: 'comprovante-endereco', nome: 'COMPROVANTE DE ENDEREÇO' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'resultado-pancary', nome: 'RESULTADO DA PESQUISA PANCARY' }
  ],
  'TI - SERVIÇOS': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ' },
    { id: 'comprovante-inscricao-cadastral', nome: 'COMPROVANTE DE INSCRIÇÃO E DE SITUAÇÃO CADASTRAL' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'politica-privacidade', nome: 'POLÍTICA DE PRIVACIDADE' },
    { id: 'termos-uso', nome: 'TERMOS DE USO' }
  ],
  'TRANSPORTADORA - NATURA': [
    { id: 'declaracao-responsabilidade', nome: 'DECLARAÇÃO (E-MAIL) DE RESPONSABILIDADE SOB O FORNECEDOR' }
  ],
  'TRANSPORTADORES': [
    { id: 'afe-correlatos', nome: 'AFE (Autorização de Funcionamento - ANVISA) - Transporte Correlatos.' },
    { id: 'afe-cosmeticos', nome: 'AFE (Autorização de Funcionamento - Anvisa) - Transporte Cosméticos.' },
    { id: 'afe-medicamentos', nome: 'AFE (Autorização de Funcionamento - ANVISA) - Transporte Medicamentos.' },
    { id: 'afe-saneantes', nome: 'AFE (Autorização de Funcionamento - ANVISA) - Transporte Saneantes.' },
    { id: 'alvara', nome: 'Alvará de Funcionamento.' },
    { id: 'alvara-licenca', nome: 'ALVARÁ/LICENÇA DE FUNCIONAMENTO' },
    { id: 'analise-credito', nome: 'ANALISE DE CREDITO' },
    { id: 'analise-credito-financeiro', nome: 'Analise de credito pelo Financeiro' },
    { id: 'antt', nome: 'ANTT' },
    { id: 'antt2', nome: 'ANTT - Agência Nacional de Transporte Terrestre' },
    { id: 'apolice-seguros', nome: 'APÓLICE DE SEGUROS' },
    { id: 'apolice-seguros2', nome: 'Apólice de Seguros.' },
    { id: 'autorizacao-ambiental', nome: 'Autorização Ambiental para o Transporte Interestadual de Produtos Perigosos.' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'avcb2', nome: 'AVCB.' },
    { id: 'cdl-dail', nome: 'CDL/DAIL (Certidão de Licença de Licenciamento/Declaração de Atividade Isenta de Licenciamento) - Dispensa Licença CETESB' },
    { id: 'certidao-pragas', nome: 'Certidão Controle de Pragas (CD - Centro de Distribuição e Veículos).' },
    { id: 'certidao-receita-federal', nome: 'Certidão da Receita Federal (CND da Receita Federal - Certidão Negativa de Débitos).' },
    { id: 'certidao-regularidade-farmaceutico', nome: 'CERTIDÃO DE REGULARIDADE (FARMACÊUTICO)' },
    { id: 'cnd-fgts', nome: 'Certidão de Regularidade com Relação ao FGTS (CND - Certidão Negativa de Débitos - Fundo de Garantia do Tempo de Serviço)' },
    { id: 'cnd-estadual', nome: 'Certidão de Regularidade Fiscal Estadual (CND Estadual - Certidão Negativa de Débitos).' },
    { id: 'cnd-municipal', nome: 'Certidão de Regularidade Fiscal Municipal (CND Municipal - Certidão Negativa de Débitos).' },
    { id: 'certidao-negativa-tributos', nome: 'Certidão Negativa de Tributos Mobiliários e Imobiliários. ' },
    { id: 'certificado-pragas-veiculos', nome: 'CERTIFICADO DE CONTROLE DE PRAGAS - VEÍCULOS' },
    { id: 'certificado-iso', nome: 'CERTIFICADO ISO 9001:2015' },
    { id: 'cnpj-atualizado', nome: 'CNPJ Atualizado (Ativo).' },
    { id: 'cnpj-atualizado2', nome: 'CNPJ Atualizado (Ativo). ' },
    { id: 'contrato-prest-servs', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇOS' },
    { id: 'contrato-prest-servs2', nome: 'Contrato de Prestação de Serviços.' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'licenca-ambiental-cetesb', nome: 'LICENÇA AMBIENTAL CETESB (OU DISPENSA)' },
    { id: 'licenca-vigilancia-anvisa', nome: 'Licença Vigilância Sanitária - ANVISA.' }
  ],
  'VALE-ALIMENTAÇÃO/VALE-TRANSPORTE': [
    { id: 'avcb', nome: 'AVCB' },
    { id: 'cartao-cnpj', nome: 'CARTÃO CNPJ' },
    { id: 'comprovante-inscricao-estadual', nome: 'COMPROVANTE DE INSCRIÇÃO ESTADUAL E SITUAÇÃO CADASTRAL' },
    { id: 'contrato-prest-serv', nome: 'CONTRATO DE PRESTAÇÃO DE SERVIÇO' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'licenca-funcionamento', nome: 'LICENÇA DE FUNCIONAMENTO' }
  ],
  'VISTORIA DAS INSTALAÇÕES ELÉTRICAS E ELABORAÇÃO DE LAUDOS ELÉTRICOS': [
    { id: 'alvara', nome: 'ALVARÁ DE FUNCIONAMENTO' },
    { id: 'autorizacao-funcionamento', nome: 'AUTORIZAÇÃO DE FUNCIONAMENTO' },
    { id: 'avcb', nome: 'AVCB' },
    { id: 'certificado-nr10', nome: 'CERTIFICADO DE NR 10' },
    { id: 'certificado-engenheiro', nome: 'CERTIFICADO DO ENGENHEIRO ELÉTRICO RESPONSÁVEL' },
    { id: 'cnpj', nome: 'CNPJ' },
    { id: 'contrato-social', nome: 'CONTRATO SOCIAL' },
    { id: 'distrato', nome: 'Distrato' },
    { id: 'ficha-cadastral', nome: 'FICHA CADASTRAL' },
    { id: 'registro-rt', nome: 'REGISTRO DE RESPONSABILIDADE TÉCNICA' }
  ],
};
